apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  namespace: retail-store
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: carts
  template:
    metadata:
      labels:
        app: carts
    spec:
      serviceAccountName: carts
      securityContext:
        fsGroup: 1000
      containers:
        - name: carts
          image: public.ecr.aws/aws-containers/retail-store-sample-cart:1.3.0
          ports:
            - containerPort: 8080
          env:
            - name: RETAIL_CART_PERSISTENCE_PROVIDER
              value: dynamodb
            - name: RETAIL_CART_PERSISTENCE_DYNAMODB_TABLE_NAME
              valueFrom:
                secretKeyRef:
                  name: carts-ddb-secret
                  key: DYNAMODB_TABLE_NAME
            - name: AWS_REGION
              value: eu-west-1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
