apiVersion: v1
kind: Service
metadata:
  name: catalog-svc
  namespace: retail-store
spec:
  selector:
    app: catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP