apiVersion: v1
kind: Service
metadata:
  name: orders-svc
  namespace: retail-store
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP