apiVersion: v1
kind: Service
metadata:
  name: ui-nodeport
  namespace: retail-store
  labels:
    app: ui
spec:
  type: NodePort
  selector:
    app: ui
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
      nodePort: 30443
